def make_raw_schema(columns: list[str]):
    return [
        {"mode": "NULLABLE", "name": col, "type": "STRING"}
        for col in columns
    ]
    

TRANSFORMED_SCHEMA = [
    {"mode": "NULLABLE", "name": "mrn", "type": "STRING"},
    {"mode": "NULLABLE", "name": "last_service_date", "type": "DATE"},
    {"mode": "NULLABLE", "name": "wave", "type": "STRING"},
    {"mode": "NULLABLE", "name": "all_mrns", "type": "STRING"},
    {"mode": "NULLABLE", "name": "practiceCode", "type": "STRING"},
    {"mode": "NULLABLE", "name": "accountClass", "type": "STRING"},
    {"mode": "NULLABLE", "name": "first_service_center", "type": "STRING"},
    {"mode": "NULLABLE", "name": "lastName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "firstName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "middleName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "suffix", "type": "STRING"},
    {"mode": "NULLABLE", "name": "otherFirstName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "otherLastName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "otherMiddleName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "otherIdentifier1", "type": "STRING"},
    {"mode": "NULLABLE", "name": "otherIdentifier1SystemName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "otherIdentifier2", "type": "STRING"},
    {"mode": "NULLABLE", "name": "otherIdentifier2SystemName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "gender", "type": "STRING"},
    {"mode": "NULLABLE", "name": "birthDate", "type": "DATE"},
    {"mode": "NULLABLE", "name": "biologicalSex", "type": "STRING"},
    {"mode": "NULLABLE", "name": "socialSecurityNumber", "type": "STRING"},
    {"mode": "NULLABLE", "name": "pronouns", "type": "STRING"},
    {"mode": "NULLABLE", "name": "sexualOrientation", "type": "STRING"},
    {"mode": "NULLABLE", "name": "race", "type": "STRING"},
    {"mode": "NULLABLE", "name": "ethnicity", "type": "STRING"},
    {"mode": "NULLABLE", "name": "disabilityStatus", "type": "STRING"},
    {"mode": "NULLABLE", "name": "maritalStatus", "type": "STRING"},
    {"mode": "NULLABLE", "name": "deceased", "type": "STRING"},
    {"mode": "NULLABLE", "name": "multipleBirth", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryAddressLine1", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryAddressLine2", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryAddressCity", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryAddressState", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryAddressPostalCode", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryAddressCountry", "type": "STRING"},
    {"mode": "NULLABLE", "name": "preferredPhoneType", "type": "STRING"},
    {"mode": "NULLABLE", "name": "preferredPhone", "type": "STRING"},
    {"mode": "NULLABLE", "name": "otherPhoneType", "type": "STRING"},
    {"mode": "NULLABLE", "name": "otherPhone", "type": "STRING"},
    {"mode": "NULLABLE", "name": "homePhone", "type": "STRING"},
    {"mode": "NULLABLE", "name": "workPhone", "type": "STRING"},
    {"mode": "NULLABLE", "name": "mobilePhone", "type": "STRING"},
    {"mode": "NULLABLE", "name": "email", "type": "STRING"},
    {"mode": "NULLABLE", "name": "electronicCommunicationOptIn", "type": "STRING"},
    {"mode": "NULLABLE", "name": "language", "type": "STRING"},
    {"mode": "NULLABLE", "name": "tagValues", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergencyContactRelationship", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergencyContactFirstName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergencyContactLastName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergencyContactMiddleName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergency_address1", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergency_address2", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergency_city", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergency_state", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergency_zip", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergencyContactPhone", "type": "STRING"},
    {"mode": "NULLABLE", "name": "emergencyContactPhoneType", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderNpi", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderFirstName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderLastName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderMiddleName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderPhone", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderFax", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderAddressLine1", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderAddressLine2", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderCity", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderState", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderPostalCode", "type": "STRING"},
    {"mode": "NULLABLE", "name": "attendingProviderCountry", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderNpi", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderFirstName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderLastName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderMiddleName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderPhone", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderFax", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderAddressLine1", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderAddressLine2", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderCity", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderState", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderPostalCode", "type": "STRING"},
    {"mode": "NULLABLE", "name": "referringProviderCountry", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderNpi", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderFirstName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderLastName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderMiddleName", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderPhone", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderFax", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderAddressLine1", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderAddressLine2", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderCity", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderState", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderPostalCode", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryProviderCountry", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryServiceFacilityId", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryCoverageStatus", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageSubscriberFirstName",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "primaryCoverageSubscriberLastName", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageSubscriberMiddleName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageSubscriberDateOfBirth",
        "type": "DATE",
    },
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageSubscriberBiologicalSex",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageSubscriberAddressLine1",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageSubscriberAddressLine2",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "primaryCoverageSubscriberCity", "type": "STRING"},
    {"mode": "NULLABLE", "name": "primaryCoverageSubscriberState", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageSubscriberPostalCode",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "primaryCoverageSubscriberCountry", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageSubscriberRelationship",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageInsurancePlanMemberId",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageInsurancePlanPayerId",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageInsurancePlanPayerName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageInsurancePlanGroupNumber",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "primaryCoverageInsurancePlanName", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageInsurancePlanNetworkType",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "primaryCoverageInsuranceTypeCode", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageInsurancePeriodStartDate",
        "type": "DATE",
    },
    {
        "mode": "NULLABLE",
        "name": "primaryCoverageInsurancePeriodEndDate",
        "type": "DATE",
    },
    {"mode": "NULLABLE", "name": "secondaryCoverageStatus", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberFirstName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberLastName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberMiddleName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberDateOfBirth",
        "type": "DATE",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberBiologicalSex",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberAddressLine1",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberAddressLine2",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "secondaryCoverageSubscriberCity", "type": "STRING"},
    {"mode": "NULLABLE", "name": "secondaryCoverageSubscriberState", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberPostalCode",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberCountry",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageSubscriberRelationship",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageInsurancePlanMemberId",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageInsurancePlanPayerId",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageInsurancePlanPayerName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageInsurancePlanGroupNumber",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageInsurancePlanName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageInsurancePlanNetworkType",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageInsuranceTypeCode",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageInsurancePeriodStartDate",
        "type": "DATE",
    },
    {
        "mode": "NULLABLE",
        "name": "secondaryCoverageInsurancePeriodEndDate",
        "type": "DATE",
    },
    {"mode": "NULLABLE", "name": "tertiaryCoverageStatus", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageSubscriberFirstName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageSubscriberLastName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageSubscriberMiddleName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageSubscriberDateOfBirth",
        "type": "DATE",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageSubscriberBiologicalSex",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageSubscriberAddressLine1",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageSubscriberAddressLine2",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "tertiaryCoverageSubscriberCity", "type": "STRING"},
    {"mode": "NULLABLE", "name": "tertiaryCoverageSubscriberState", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageSubscriberPostalCode",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "tertiaryCoverageSubscriberCountry", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageSubscriberRelationship",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageInsurancePlanMemberId",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageInsurancePlanPayerId",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageInsurancePlanPayerName",
        "type": "STRING",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageInsurancePlanGroupNumber",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "tertiaryCoverageInsurancePlanName", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageInsurancePlanNetworkType",
        "type": "STRING",
    },
    {"mode": "NULLABLE", "name": "tertiaryCoverageInsuranceTypeCode", "type": "STRING"},
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageInsurancePeriodStartDate",
        "type": "DATE",
    },
    {
        "mode": "NULLABLE",
        "name": "tertiaryCoverageInsurancePeriodEndDate",
        "type": "DATE",
    },
    {"mode": "NULLABLE", "name": "patientCreateStamp", "type": "STRING"},
    {"mode": "NULLABLE", "name": "patientLastModifiedStamp", "type": "DATE"},
    {"mode": "NULLABLE", "name": "patientRecordStatus", "type": "STRING"},
    {"mode": "NULLABLE", "name": "duplicatePatientMRN", "type": "STRING"},
    {"mode": "NULLABLE", "name": "deactivationNote", "type": "STRING"},
    {"mode": "NULLABLE", "name": "deactivationDate", "type": "STRING"},
    {"mode": "NULLABLE", "name": "deactivationReason", "type": "STRING"},
]


RAW_SCHEMA = [
    {'mode': 'NULLABLE', 'name': 'mrn', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'practiceCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'accountClass', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'first_service_center', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'last_service_date', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'lastName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'firstName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'middleName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'suffix', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'otherFirstName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'otherLastName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'otherMiddleName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'otherIdentifier1', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'otherIdentifier1SystemName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'otherIdentifier2', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'otherIdentifier2SystemName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'gender', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'birthDate', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'biologicalSex', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'socialSecurityNumber', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'pronouns', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'sexualOrientation', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'race', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'ethnicity', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'disabilityStatus', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'maritalStatus', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'deceased', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'multipleBirth', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryAddressLine1', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryAddressLine2', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryAddressCity', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryAddressState', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryAddressPostalCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryAddressCountry', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'preferredPhoneType', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'preferredPhone', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'otherPhoneType', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'otherPhone', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'homePhone', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'workPhone', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'mobilePhone', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'email', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'electronicCommunicationOptIn', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'language', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tagValues', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergencyContactRelationship', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergencyContactFirstName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergencyContactLastName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergencyContactMiddleName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergency_address1', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergency_address2', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergency_city', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergency_state', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergency_zip', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergencyContactPhone', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'emergencyContactPhoneType', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderNpi', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderFirstName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderLastName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderMiddleName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderPhone', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderAddressLine1', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderAddressLine2', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderCity', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderState', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderPostalCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'attendingProviderCountry', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderNpi', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderFirstName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderLastName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderMiddleName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderPhone', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderAddressLine1', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderAddressLine2', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderCity', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderState', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderPostalCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'referringProviderCountry', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderNpi', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderFirstName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderLastName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderMiddleName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderPhone', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderAddressLine1', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderAddressLine2', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderCity', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderState', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderPostalCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryProviderCountry', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryServiceFacilityId', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageStatus', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberFirstName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberLastName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberMiddleName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberDateOfBirth', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberBiologicalSex', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberAddressLine1', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberAddressLine2', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberCity', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberState', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberPostalCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberCountry', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageSubscriberRelationship', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageInsurancePlanMemberId', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageInsurancePlanPayerId', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageInsurancePlanPayerName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageInsurancePlanGroupNumber', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageInsurancePlanName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageInsurancePlanNetworkType', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageInsuranceTypeCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageInsurancePeriodStartDate', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'primaryCoverageInsurancePeriodEndDate', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageStatus', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberFirstName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberLastName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberMiddleName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberDateOfBirth', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberBiologicalSex', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberAddressLine1', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberAddressLine2', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberCity', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberState', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberPostalCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberCountry', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageSubscriberRelationship', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageInsurancePlanMemberId', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageInsurancePlanPayerId', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageInsurancePlanPayerName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageInsurancePlanGroupNumber', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageInsurancePlanName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageInsurancePlanNetworkType', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageInsuranceTypeCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageInsurancePeriodStartDate', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'secondaryCoverageInsurancePeriodEndDate', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageStatus', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberFirstName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberLastName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberMiddleName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberDateOfBirth', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberBiologicalSex', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberAddressLine1', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberAddressLine2', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberCity', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberState', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberPostalCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberCountry', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageSubscriberRelationship', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageInsurancePlanMemberId', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageInsurancePlanPayerId', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageInsurancePlanPayerName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageInsurancePlanGroupNumber', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageInsurancePlanName', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageInsurancePlanNetworkType', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageInsuranceTypeCode', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageInsurancePeriodStartDate', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'tertiaryCoverageInsurancePeriodEndDate', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'patientCreateStamp', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'wave', 'type': 'STRING'}, {'mode': 'NULLABLE', 'name': 'failure_reason', 'type': 'STRING'}
]

PPG_SCHEMA = [
    {"mode": "NULLABLE", "name": "ingest_payer_name", "type": "STRING"},
    {"mode": "NULLABLE", "name": "ingest_plan_name", "type": "STRING"},
    {"mode": "NULLABLE", "name": "candid_payer_plan_group", "type": "STRING"},
]
